name: Run Selenium Script with Anti-CAPTCHA

on:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"  # Menjadwalkan workflow untuk berjalan setiap 5 menit
  workflow_dispatch:

jobs:
  run-bb-py:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install google-api-python-client google-auth-httplib2 google-auth-oauthlib anticaptchaofficial selenium gitpython

      - name: Download ChromeDriver
        run: |
          $chrome_version = (Invoke-WebRequest -Uri "https://chromedriver.storage.googleapis.com/LATEST_RELEASE").Content
          Invoke-WebRequest -Uri "https://chromedriver.storage.googleapis.com/$chrome_version/chromedriver_win32.zip" -OutFile "chromedriver.zip"
          Expand-Archive -Path chromedriver.zip -DestinationPath .

      - name: Set up Chrome browser
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'latest'

      - name: Add ChromeDriver to PATH
        run: |
          echo "$(pwd)\chromedriver.exe" >> $GITHUB_PATH

      - name: Run Selenium Script
        env:
          YOUR_ANTI_CAPTCHA_API_KEY: ${{ secrets.ANTICAPTCHA_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python bb.py
